sudo: required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t milindl/docker-react .

script:
    - docker run -e CI=true milindl/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "docker-react-env"
    bucket_name: "elasticbeanstalk-us-west-2-971647868236"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id:
        secure: "$AWS_ACCESS_KEY"
    secrect_access_key:
        secure "$AWS_SECRET_KEY"
